# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20170820_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
